"""Create initial habit tracker tables structure

Revision ID: 3c717780d279
Revises: 
Create Date: 2026-05-11 14:21:57.846828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c717780d279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('user_account_identifier', sa.Integer(), nullable=False),
    sa.Column('telegram_user_identifier', sa.String(), nullable=False),
    sa.Column('hashed_user_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_account_identifier')
    )
    op.create_index(op.f('ix_user_accounts_telegram_user_identifier'), 'user_accounts', ['telegram_user_identifier'], unique=True)
    op.create_index(op.f('ix_user_accounts_user_account_identifier'), 'user_accounts', ['user_account_identifier'], unique=False)
    op.create_table('user_habits',
    sa.Column('habit_identifier', sa.Integer(), nullable=False),
    sa.Column('habit_title_name', sa.String(), nullable=False),
    sa.Column('total_execution_success_count', sa.Integer(), nullable=True),
    sa.Column('is_habit_deleted_status', sa.Boolean(), nullable=True),
    sa.Column('owner_account_foreign_key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_account_foreign_key'], ['user_accounts.user_account_identifier'], ),
    sa.PrimaryKeyConstraint('habit_identifier')
    )
    op.create_index(op.f('ix_user_habits_habit_identifier'), 'user_habits', ['habit_identifier'], unique=False)
    op.create_table('habit_execution_logs',
    sa.Column('log_record_identifier', sa.Integer(), nullable=False),
    sa.Column('target_habit_foreign_key', sa.Integer(), nullable=True),
    sa.Column('habit_execution_date', sa.Date(), nullable=False),
    sa.Column('is_habit_completed_successfully', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['target_habit_foreign_key'], ['user_habits.habit_identifier'], ),
    sa.PrimaryKeyConstraint('log_record_identifier')
    )
    op.create_index(op.f('ix_habit_execution_logs_log_record_identifier'), 'habit_execution_logs', ['log_record_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habit_execution_logs_log_record_identifier'), table_name='habit_execution_logs')
    op.drop_table('habit_execution_logs')
    op.drop_index(op.f('ix_user_habits_habit_identifier'), table_name='user_habits')
    op.drop_table('user_habits')
    op.drop_index(op.f('ix_user_accounts_user_account_identifier'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_telegram_user_identifier'), table_name='user_accounts')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
